language: python
python:
  - "3.6"
cache: pip
services:
  - docker
addons:
  hosts:
    - credstore
    - vault
    - security_policy_manager
    - crypto_engine
    - iivr
  apt:
    packages:
      - lynx
install:
  - pip install -r requirements.txt
  - pip install docutils
  - pip install pyopenssl
  - pip install robotframework
before_script:
  - docker run -d --cap-add=IPC_LOCK -v $(pwd)/test/:/vault/ --name vault -p 127.0.0.1:8200:8200 vault:1.0.3 server
  - docker exec -t vault netstat -antup
  - |
      gunicorn -b 0.0.0.0:5003 --log-file=- app:app &
      SERVER_PID=$!
script:
  - robot test/test_script.rst
after_script:
  - docker logs vault
  - cat output.xml
  - lynx -dump report.html
  - lynx -dump log.html
  - kill $SERVER_PID
